"use client";
import {useMemo,useState} from "react";

type Key="reiki"|"landscape"|"gallery"|"cleaning"|"shop"|"nails"|"members";
const brands:Record<Key,{name:string;type:string}>={
  reiki:{name:"LuxeBeorn",type:"Distance Reiki"},landscape:{name:"Andrew Thorn",type:"Landscaping"},
  gallery:{name:"Morrow Studio",type:"Art & Editions"},cleaning:{name:"Neat & Kind",type:"Home Cleaning"},
  shop:{name:"Field Supply",type:"Outdoor Store"},nails:{name:"Afterglow",type:"Nail Studio"},
  members:{name:"The Good Work Club",type:"Membership"}
};
const keys=Object.keys(brands) as Key[];

export default function Home(){
  const[active,setActive]=useState<Key>("reiki"),[picker,setPicker]=useState(false),[before,setBefore]=useState(false),[evidence,setEvidence]=useState(false);
  const choose=(k:Key)=>{setActive(k);setPicker(false);setBefore(false);window.scrollTo({top:0,behavior:"smooth"})};
  return <main className="showcase">
    <aside className="wm-toolbar">
      <button className="wm-brand" onClick={()=>setPicker(!picker)}><i>W</i><span><b>The Website Mill</b><small>Seven businesses. Seven real design systems.</small></span></button>
      <div className="wm-compare"><button className={before?"on":""} onClick={()=>setBefore(true)}>Before</button><button className={!before?"on":""} onClick={()=>setBefore(false)}>Rebuilt</button></div>
      <button className="wm-evidence" onClick={()=>setEvidence(!evidence)}>What changed <span>↗</span></button>
      <button className="wm-switch" onClick={()=>setPicker(!picker)}><small>Viewing</small><b>{brands[active].name}</b><span>⌄</span></button>
      <div className={`wm-picker ${picker?"open":""}`}><header><div><small>The Website Mill showcase</small><h2>Choose a business</h2></div><button onClick={()=>setPicker(false)}>Close ×</button></header>{keys.map((k,i)=><button key={k} className={active===k?"on":""} onClick={()=>choose(k)}><span>0{i+1}</span><div><b>{brands[k].name}</b><small>{brands[k].type}</small></div><em>↗</em></button>)}</div>
    </aside>
    {evidence&&<Evidence active={active} close={()=>setEvidence(false)}/>}
    {before?<LegacyBefore brand={brands[active]}/>:<Site active={active}/>}
  </main>
}

function Site({active}:{active:Key}){
  if(active==="reiki")return <Reiki/>;
  if(active==="landscape")return <Landscape/>;
  if(active==="gallery")return <Gallery/>;
  if(active==="cleaning")return <Cleaning/>;
  if(active==="shop")return <Shop/>;
  if(active==="nails")return <Nails/>;
  return <Members/>;
}

function Evidence({active,close}:{active:Key;close:()=>void}){
 const changes:Record<Key,string[][]>={
  reiki:[["Generic spa language","Grounded session selector"],["Repeated service cards","Editorial treatment journey"],["No practical reassurance","Clear distance-Reiki process"]],
  landscape:[["Brochure-style hero","Project-led trade layout"],["Decorative services","Workmanship and coverage detail"],["Generic enquiry","Structured site-visit request"]],
  gallery:[["Service-business template","Image-first digital gallery"],["Cards competing with artwork","Catalogue labels and masonry"],["No buying context","Edition and availability detail"]],
  cleaning:[["Vague contact journey","Instant interactive estimate"],["Luxury visual language","Bright, scannable service UI"],["No inclusions","Room-by-room checklist"]],
  shop:[["Six products in service cards","Scalable commerce catalogue"],["Basic category buttons","Search, sorting and filter rail"],["No basket feedback","Functional bag and delivery target"]],
  nails:[["Muted salon template","Social-first portfolio collage"],["Generic booking button","Art-tier price selector"],["No nail-health detail","Duration, removal and care cues"]],
  members:[["Static coaching brochure","Public site plus real portal"],["Fake locked cards","Filterable resource library"],["No retention value","Progress and upcoming sessions"]]
 };
 return <div className="wm-drawer"><header><div><small>Build evidence · {brands[active].name}</small><h2>Before → rebuilt</h2></div><button onClick={close}>Close ×</button></header><p>The previous shared-template version remains available through <b>Before</b>. The rebuilt version changes the structure, not only the colour.</p>{changes[active].map((x,i)=><article key={x[0]}><span>0{i+1}</span><div><small>Before</small><b>{x[0]}</b></div><i>→</i><div><small>Rebuilt</small><b>{x[1]}</b></div></article>)}</div>
}

function LegacyBefore({brand}:{brand:{name:string;type:string}}){
 return <div className="legacy"><header><b>{brand.name}</b><nav>About　 Services　 Stories　 <button>Book now</button></nav></header><section className="legacy-hero"><small>WELCOME TO OUR WEBSITE</small><h1>Professional {brand.type.toLowerCase()} services.</h1><p>We provide high-quality services at competitive prices. Contact us today to find out more.</p><button>Contact us →</button></section><section className="legacy-story"><div><small>WHY {brand.name.toUpperCase()}</small><h2>Quality service you can trust.</h2></div><p>We believe in providing excellent customer service and working closely with every client.</p></section><section className="legacy-cards"><h2>Ways we can help.</h2><div>{["Service one","Service two","Service three"].map(x=><article key={x}><span>⌁</span><h3>{x}</h3><p>Professional support tailored to your needs. Get in touch to learn more.</p><a>Explore & book ↗</a></article>)}</div></section><section className="legacy-quote">“Excellent service from start to finish.”</section><footer>© 2026 {brand.name} · Demo before state</footer></div>
}

function Reiki(){
 const[session,setSession]=useState("reset"),[faq,setFaq]=useState(0);
 const options={reset:["The Reset","30 minutes","£35","For a busy mind or heavy day."],restore:["Deep Restore","60 minutes","£60","For space, reflection and deeper rest."],path:["Lightkeeper Path","4 sessions","£210","For steady support through a season of change."]};
 const s=options[session as keyof typeof options];
 return <div className="reiki-site">
  <header className="r-nav"><a><i>✦</i><b>LuxeBeorn</b><small>Light · Warrior · Reiki</small></a><nav><a href="#r-story">Our story</a><a href="#r-how">How it works</a><a href="#r-sessions">Sessions</a><button>Book gently →</button></nav></header>
  <section className="r-hero"><div className="r-copy"><small>DISTANCE REIKI · FROM YOUR OWN SPACE</small><h1>Come home to your own energy.</h1><p>Grounded, personal Reiki for busy minds and heavy weeks. No performance. No pressure. Just a little room to breathe.</p><div><button>Find your session →</button><a href="#r-how">What actually happens?</a></div></div><figure><img src="https://images.unsplash.com/photo-1545389336-cf090694435e?auto=format&fit=crop&w=1200&q=88" alt="A calm, sunlit space for rest"/><figcaption>You can arrive exactly as you are.</figcaption></figure></section>
  <section className="r-story" id="r-story"><aside>Lucy <i>means</i> light.<br/>Finley <i>means</i> warrior.</aside><div><small>THE HEART OF LUXEBEORN</small><h2>Softness and strength belong together.</h2><p>LuxeBeorn was named for our children and built around a simple belief: rest does not make you less strong. Sessions are calm, confidential and explained in plain English.</p></div></section>
  <section className="r-how" id="r-how"><header><small>DISTANCE REIKI, MADE CLEAR</small><h2>Rest where you feel safest.</h2></header><div>{[["01","We talk","A short message or call about what you need—without having to over-explain."],["02","You settle","Stay at home, get comfortable and switch off notifications. Nothing special required."],["03","I practise","I hold the Reiki session at our agreed time, followed by a gentle written check-in."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section className="r-sessions" id="r-sessions"><div><small>CHOOSE BY WHAT YOU NEED</small><h2>How much space would feel helpful?</h2><div className="r-tabs">{Object.entries(options).map(([k,v])=><button key={k} className={session===k?"on":""} onClick={()=>setSession(k)}>{v[0]}</button>)}</div></div><article><small>{s[1]}</small><h3>{s[0]}</h3><p>{s[3]}</p><strong>{s[2]}</strong><button>Choose this session →</button></article></section>
  <section className="r-faq"><header><small>NO MYSTERY</small><h2>Practical questions.</h2></header>{["Do I need to believe in Reiki?","What will I feel?","Can Reiki replace medical care?"].map((q,i)=><article key={q}><button onClick={()=>setFaq(faq===i?-1:i)}><b>{q}</b><span>{faq===i?"−":"+"}</span></button>{faq===i&&<p>{i===0?"No. Curiosity is enough. You do not need to visualise, meditate or feel anything specific.":i===1?"Everyone is different. You may feel warmth, calm, emotion—or simply have a quiet hour. There is no correct response.":"No. Reiki is complementary wellbeing support and never a replacement for qualified medical advice or treatment."}</p>}</article>)}</section>
  <footer className="r-footer"><h2>A little room for you.</h2><button>Book your first session →</button><small>LuxeBeorn · Distance Reiki · Demonstration website</small></footer>
 </div>
}

function Landscape(){
 const[filter,setFilter]=useState("All"),[slide,setSlide]=useState(55);
 const projects=[["Patios","The family terrace","https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=900&q=85"],["Fencing","A stronger boundary","https://images.unsplash.com/photo-1598902108854-10e335adac99?auto=format&fit=crop&w=900&q=85"],["Full gardens","Garden built for living","https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=900&q=85"]];
 return <div className="land-site"><header className="l-top"><span>Andrew Thorn Landscaping</span><p>Cambridgeshire & surrounding villages</p><a>Call 07700 900 246</a></header><nav className="l-nav"><b>AT<span>/</span>LANDSCAPING</b><div>Services　 Work　 About</div><button>Request a site visit</button></nav>
 <section className="l-hero"><div><small>30+ YEARS OF HANDS-ON EXPERIENCE</small><h1>Built properly.<br/>Finished with care.</h1><p>Patios, fencing and complete gardens from one experienced local landscaper.</p><button>Request a free visit →</button><ul><li>Fully insured</li><li>Clear written quotes</li><li>Tidy, respectful work</li></ul></div><img src="https://images.unsplash.com/photo-1598902108854-10e335adac99?auto=format&fit=crop&w=1200&q=88" alt="Landscaper building a timber garden structure"/></section>
 <section className="l-services"><header><span>01 / WHAT I DO</span><h2>Solid work.<br/>Straight answers.</h2></header>{[["Patios & paving","Preparation, drainage and a finish that stays level."],["Fencing & gates","Strong boundaries, straight lines and dependable timber."],["Full garden builds","Groundworks, turf, sleepers and planting managed properly."]].map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p><a>See details →</a></article>)}</section>
 <section className="l-ba"><div><small>REAL TRANSFORMATION</small><h2>From unused patch to family garden.</h2><p>Drag the control to compare the same space before and after a full six-week build.</p></div><figure><img src="https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=1200&q=85" alt="Finished landscaped garden"/><div style={{width:`${slide}%`}}><img src="https://images.unsplash.com/photo-1599685315640-9ceab2f581ca?auto=format&fit=crop&w=1200&q=80" alt="Garden before landscaping"/></div><input aria-label="Compare before and after" type="range" min="5" max="95" value={slide} onChange={e=>setSlide(Number(e.target.value))}/></figure></section>
 <section className="l-work"><header><div><small>SELECTED LOCAL WORK</small><h2>Judge the finish.</h2></div><div>{["All","Patios","Fencing","Full gardens"].map(x=><button className={filter===x?"on":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></header><div>{projects.filter(x=>filter==="All"||x[0]===filter).map(x=><figure key={x[1]}><img src={x[2]} alt={x[1]}/><figcaption><small>{x[0]}</small><b>{x[1]}</b></figcaption></figure>)}</div></section>
 <section className="l-quote"><div><small>FREE SITE VISIT</small><h2>Tell me what needs doing.</h2><p>I’ll arrange a convenient visit, look at the ground properly and provide a clear written quote.</p></div><form><label>Job type<select><option>Choose one</option><option>Patio or paving</option><option>Fencing</option><option>Full garden</option></select></label><label>Postcode<input placeholder="PE28"/></label><label>Ideal timing<select><option>Flexible</option><option>Within 1–3 months</option><option>Within 3–6 months</option></select></label><button>Request my visit →</button></form></section>
 </div>
}

const art=[["Salt Air I","Original","£640","https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=900&q=88"],["Held Light","Edition of 30","£145","https://images.unsplash.com/photo-1578301978162-7aae4d755744?auto=format&fit=crop&w=900&q=88"],["Soft Ground","Photography","£95","https://images.unsplash.com/photo-1577083288073-40892c0860a4?auto=format&fit=crop&w=900&q=88"],["After Rain","Original","£780","https://images.unsplash.com/photo-1577083552431-6e5fd01988a5?auto=format&fit=crop&w=900&q=88"]];
function Gallery(){
 const[view,setView]=useState<number|null>(null),[kind,setKind]=useState("All");const shown=art.filter(x=>kind==="All"||x[1].includes(kind));
 return <div className="art-site"><header className="a-nav"><b>MORROW<span>STUDIO</span></b><nav>COLLECTION　 ARTIST　 COMMISSIONS</nav><button>Bag 0</button></header><section className="a-intro"><p>BRITISH ARTIST · ORIGINALS & SMALL EDITIONS</p><h1>Work for rooms<br/>with a point of view.</h1><aside>Original paintings, archival editions and quiet photographic studies made in a small British studio.</aside></section><section className="a-feature"><img src={art[0][3]} alt="Featured abstract artwork"/><div><small>NEW ORIGINAL · 01</small><h2>Salt Air I</h2><p>Oil, wax and ground pigment on linen.<br/>76 × 102 cm · Signed · Unique</p><strong>£640</strong><button onClick={()=>setView(0)}>View the work →</button></div></section><section className="a-collection"><header><h2>Available work</h2><div>{["All","Original","Edition","Photography"].map(x=><button className={kind===x?"on":""} onClick={()=>setKind(x)} key={x}>{x}</button>)}</div></header><div className="a-grid">{shown.map((x,i)=><figure key={x[0]} onClick={()=>setView(art.indexOf(x))}><img src={x[3]} alt={x[0]}/><figcaption><div><b>{x[0]}</b><small>{x[1]}</small></div><span>{x[2]}</span></figcaption></figure>)}</div></section><section className="a-statement"><span>“</span><h2>I paint the memory of a place, not the map of it.</h2><p>Studio notes · August 2026</p></section><footer className="a-footer">MORROW STUDIO <span>Original work · Archival editions · Commissions</span></footer>{view!==null&&<div className="a-modal"><button onClick={()=>setView(null)}>Close ×</button><img src={art[view][3]} alt={art[view][0]}/><div><small>{art[view][1]}</small><h2>{art[view][0]}</h2><p>Archival materials · Signed by the artist<br/>Certificate of authenticity included</p><strong>{art[view][2]}</strong><button>Enquire / purchase →</button></div></div>}</div>
}

function Cleaning(){
 const[beds,setBeds]=useState(3),[baths,setBaths]=useState(1),[freq,setFreq]=useState("Fortnightly"),[room,setRoom]=useState("Kitchen");const base=22+beds*6+baths*8;const price=Math.round(base*(freq==="Weekly"?.88:freq==="One-off"?1.5:1));
 return <div className="clean-site"><header className="c-nav"><b>neat<span>&</span>kind.</b><nav>What’s included　 Our team　 Reviews</nav><button>Book a clean</button></header><section className="c-hero"><div><span className="c-pill">✓ Fully insured local team</span><h1>Come home<br/>to <i>done.</i></h1><p>Friendly, reliable home cleaning with familiar faces, clear prices and absolutely no judgement.</p><div className="c-trust"><b>4.9 ★</b><span>From 180+ local cleans</span></div></div><aside><small>QUICK ESTIMATE</small><h2>What would your clean cost?</h2><label>Bedrooms <div><button onClick={()=>setBeds(Math.max(1,beds-1))}>−</button><b>{beds}</b><button onClick={()=>setBeds(beds+1)}>+</button></div></label><label>Bathrooms <div><button onClick={()=>setBaths(Math.max(1,baths-1))}>−</button><b>{baths}</b><button onClick={()=>setBaths(baths+1)}>+</button></div></label><div className="c-frequency">{["Weekly","Fortnightly","One-off"].map(x=><button className={freq===x?"on":""} onClick={()=>setFreq(x)} key={x}>{x}</button>)}</div><footer><span>Estimated from</span><strong>£{price}</strong><button>Check availability →</button></footer></aside></section><section className="c-included"><header><small>NO VAGUE PROMISES</small><h2>See exactly what’s included.</h2></header><div className="c-rooms">{["Kitchen","Bathroom","Bedroom","Living space"].map(x=><button className={room===x?"on":""} onClick={()=>setRoom(x)} key={x}>{x}</button>)}</div><article><div><span>{room==="Kitchen"?"✦":room==="Bathroom"?"◉":room==="Bedroom"?"☁":"⌂"}</span><h3>{room}</h3></div><ul>{["Surfaces carefully cleaned","Floors vacuumed and mopped","Bins emptied and reset","High-touch areas sanitised","Finishing details checked"].map(x=><li key={x}>✓ {x}</li>)}</ul></article></section><section className="c-team"><img src="https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1000&q=85" alt="Friendly professional cleaner at work"/><div><small>PEOPLE YOU CAN TRUST</small><h2>Familiar faces. Kind standards.</h2><p>Our team is vetted, insured and employed by us. Wherever possible, the same cleaner returns to your home.</p><div><b>✓ Vetted team</b><b>✓ Supplies included</b><b>✓ Satisfaction promise</b></div></div></section><footer className="c-footer"><h2>Your weekend has better plans.</h2><button>Get my estimate →</button></footer></div>
}

const goods=[["Kestrel Rolltop","Packs","£84","https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=85"],["Ridgeline Overshirt","Wear","£68","https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=85"],["Ember Brew Kit","Camp","£42","https://images.unsplash.com/photo-1526401485004-2aa7d95f6df6?auto=format&fit=crop&w=800&q=85"],["Daybreak Pack","Packs","£110","https://images.unsplash.com/photo-1622260614153-03223fb72052?auto=format&fit=crop&w=800&q=85"],["Trail Blanket","Camp","£76","https://images.unsplash.com/photo-1526481280695-3c687fd643ed?auto=format&fit=crop&w=800&q=85"],["All-Weather Cap","Wear","£28","https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=800&q=85"]];
function Shop(){
 const[q,setQ]=useState(""),[cat,setCat]=useState("All"),[max,setMax]=useState(120),[sort,setSort]=useState("Featured"),[bag,setBag]=useState<string[]>([]),[open,setOpen]=useState(false);let shown=goods.filter(x=>(cat==="All"||x[1]===cat)&&Number(x[2].slice(1))<=max&&x[0].toLowerCase().includes(q.toLowerCase()));if(sort==="Price low")shown=[...shown].sort((a,b)=>Number(a[2].slice(1))-Number(b[2].slice(1)));
 return <div className="shop-site"><header className="s-nav"><button>☰ SHOP</button><b>FIELD/SUPPLY</b><div><button>⌕ Search</button><button onClick={()=>setOpen(true)}>Bag [{bag.length}]</button></div></header><section className="s-hero"><div><small>FIELD NOTE / 026</small><h1>Built to go.<br/>Made to stay.</h1><p>Repairable outdoor goods for slower weekends and longer trails.</p><button>Shop the field edit →</button></div><aside><span>TESTED OUTSIDE</span><b>01 / KESTREL SERIES</b></aside></section><section className="s-cats">{["Camp","Packs","Wear"].map((x,i)=><button key={x} onClick={()=>setCat(x)}><span>0{i+1}</span><b>{x}</b><em>Explore →</em></button>)}</section><section className="s-store"><aside><h2>Filter field</h2><label>Search<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products"/></label><div><b>Category</b>{["All","Camp","Packs","Wear"].map(x=><button className={cat===x?"on":""} onClick={()=>setCat(x)} key={x}>□ {x}</button>)}</div><label>Maximum £{max}<input type="range" min="25" max="120" value={max} onChange={e=>setMax(Number(e.target.value))}/></label><button onClick={()=>{setQ("");setCat("All");setMax(120)}}>Clear all</button></aside><main><header><span>{shown.length} products</span><select value={sort} onChange={e=>setSort(e.target.value)}><option>Featured</option><option>Price low</option></select></header><div>{shown.map(x=><article key={x[0]}><figure><img src={x[3]} alt={x[0]}/><button onClick={()=>setBag([...bag,x[0]])}>Quick add +</button></figure><small>{x[1]} · In stock</small><h3>{x[0]}</h3><b>{x[2]}</b></article>)}</div></main></section>{open&&<aside className="s-bag"><header><h2>Your field bag</h2><button onClick={()=>setOpen(false)}>Close ×</button></header>{bag.length?bag.map((x,i)=><article key={i}><b>{x}</b><button onClick={()=>setBag(bag.filter((_,j)=>j!==i))}>Remove</button></article>):<p>Your bag is ready for an adventure.</p>}<footer><p>{bag.length>=2?"Free delivery unlocked":"Add another item to unlock free delivery"}</p><button>Continue to checkout →</button></footer></aside>}</div>
}

const nailImgs=["https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=88","https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=800&q=88","https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=800&q=88","https://images.unsplash.com/photo-1607779097040-26e80aa78e66?auto=format&fit=crop&w=800&q=88"];
function Nails(){
 const[tier,setTier]=useState(1),[style,setStyle]=useState("All");const tiers=[["Clean girl","£38","60 min"],["Statement","£48","75 min"],["Main character","£62","105 min"]];
 return <div className="nail-site"><header className="n-nav"><b>AFTERGLOW<span>NAIL STUDIO</span></b><nav>SETS　 MENU　 STUDIO</nav><button>BOOK NOW ↗</button></header><section className="n-hero"><div><span>BIAB · NAIL ART · CAMBRIDGE</span><h1>Tiny canvases.<br/><i>Main-character</i> energy.</h1><p>Healthy natural nails and detailed art in a relaxed private studio.</p><button>Book your set ↗</button></div><div className="n-collage">{nailImgs.slice(0,3).map((x,i)=><img key={x} className={"n"+i} src={x} alt="Afterglow nail art"/>)}</div><b className="n-sticker">NAIL<br/>OBSESSED</b></section><section className="n-feed"><header><small>FRESH FROM THE STUDIO</small><h2>Saved it? Let’s make it yours.</h2><div>{["All","BIAB","French","Chrome","Art"].map(x=><button className={style===x?"on":""} onClick={()=>setStyle(x)} key={x}>{x}</button>)}</div></header><div>{nailImgs.map((x,i)=><figure key={x}><img src={x} alt={`Recent ${style==="All"?"nail":style} set ${i+1}`}/><figcaption>{["Cherry chrome","Aura French","Miniature art","Milky details"][i]}</figcaption></figure>)}</div></section><section className="n-menu"><div><small>CHOOSE YOUR ART LEVEL</small><h2>Your idea.<br/>The right appointment.</h2><p>Pick the closest tier now—we can confirm the details before your visit.</p></div><article><div>{tiers.map((x,i)=><button className={tier===i?"on":""} onClick={()=>setTier(i)} key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></button>)}</div><h3>{tiers[tier][0]}</h3><p>{tier===0?"One colour, glazed finish or simple French.":tier===1?"Chrome, aura, cuffs or art across up to five nails.":"Detailed art across every nail, layered effects or character work."}</p><footer><b>{tiers[tier][1]}</b><span>{tiers[tier][2]}</span><button>Book this tier →</button></footer></article></section><section className="n-care"><div><small>PRETTY, BUT PROPER</small><h2>Nail health is part of the look.</h2></div><ul><li>✓ Detailed prep and hygiene</li><li>✓ Safe removal—never picked or peeled</li><li>✓ Transparent timing and deposits</li></ul></section><a className="n-mobile-book">BOOK YOUR SET ↗</a></div>
}

function Members(){
 const[inside,setInside]=useState(false),[topic,setTopic]=useState("All"),[done,setDone]=useState<string[]>([]);const resources=[["Visibility","Workshop","The one-page visibility plan"],["Sales","Template","Warm follow-up messages"],["Planning","Playbook","Build a referral rhythm"],["Mindset","Audio","A calmer working week"]];
 if(inside)return <div className="portal"><aside><b>GOOD/W<span>MEMBER SPACE</span></b><nav><a className="on">⌂ Overview</a><a>▣ Library</a><a>◷ Sessions</a><a>✓ My progress</a></nav><button onClick={()=>setInside(false)}>← View public site</button></aside><main><header><div><small>SUNDAY 16 AUGUST</small><h1>Good evening, Joe.</h1></div><span>3 week streak 🔥</span></header><section className="p-progress"><div><small>AUGUST FOCUS</small><h2>Build a referral rhythm that feels human.</h2><p>{done.length}/4 resources complete</p></div><i style={{"--p":`${done.length*25}%`} as React.CSSProperties}></i></section><section className="p-library"><header><h2>Your library</h2><div>{["All","Visibility","Sales","Planning"].map(x=><button className={topic===x?"on":""} onClick={()=>setTopic(x)} key={x}>{x}</button>)}</div></header><div>{resources.filter(x=>topic==="All"||x[0]===topic).map(x=><article className={done.includes(x[2])?"done":""} key={x[2]}><small>{x[0]} · {x[1]}</small><h3>{x[2]}</h3><button onClick={()=>setDone(done.includes(x[2])?done.filter(y=>y!==x[2]):[...done,x[2]])}>{done.includes(x[2])?"✓ Completed":"Mark complete"}</button></article>)}</div></section><section className="p-event"><div><small>NEXT LIVE SESSION</small><h2>Quiet co-working</h2><p>Wednesday · 10:00–11:30</p></div><button>Save my place →</button></section></main></div>;
 return <div className="member-site"><header className="m-nav"><b>THE GOOD WORK CLUB</b><nav>What’s inside　 This month　 Pricing</nav><button onClick={()=>setInside(true)}>Member login ↗</button></header><section className="m-hero"><div><span>FOR INDEPENDENT BUSINESS OWNERS</span><h1>Less noise.<br/>More <i>useful</i> progress.</h1><p>A practical monthly membership for choosing the right work—and actually finishing it.</p><div><button>Join for £29/month →</button><button onClick={()=>setInside(true)}>Explore the member demo</button></div></div><aside><small>THIS MONTH INSIDE</small><h2>Build a referral rhythm that feels human.</h2><ul><li>01 · 45-minute playbook</li><li>02 · Live working session</li><li>03 · Follow-up templates</li></ul><button onClick={()=>setInside(true)}>Open member preview →</button></aside></section><section className="m-strip"><b>No hustle theatre.</b><b>No 47-hour course.</b><b>No falling behind.</b></section><section className="m-month"><header><small>A REAL MONTH, NOT A CONTENT DUMP</small><h2>A simple rhythm that keeps moving.</h2></header><div>{[["WEEK 01","Choose","One clear playbook and a realistic priority."],["WEEK 02","Work","A live room to make progress with support."],["WEEK 03","Apply","Templates that turn the idea into action."],["WEEK 04","Review","Notice what worked and choose what is next."]].map(x=><article key={x[0]}><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><section className="m-portal"><div><small>THE DIFFERENCE IS INSIDE</small><h2>A member area built for doing—not browsing.</h2><p>Filter resources, track progress and register for working sessions in a real interactive demo.</p><button onClick={()=>setInside(true)}>Enter as a demo member →</button></div><div className="m-ui"><span>August focus　 50% complete</span><b>Build a referral rhythm</b><i></i><small>Next: Quiet co-working · Wednesday</small></div></section><footer className="m-footer"><h2>Make good work easier to do.</h2><button>Join the club →</button></footer></div>
}
